/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a401f59a4e5379af222fce46c53e1a90)

declare namespace Cloudflare {
  interface Env {
    MYBROWSER: Fetcher;
  }
}
